### ISSUE TITLE
EMS not starting properly

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/nebulous#2]
During the deployment of an application, EMS didn't create the deamons for the different PODs.

ems-server was installed:

![image](https://github.com/eu-nebulous/nebulous/assets/172278014/1afb7a91-82ba-4f74-97e2-d3b85156ae20)

And it showed the following error:

```text
2024-06-26T10:27:04.181Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.b.s.c.c.ClusteringCoordinator    : Cluster Detector class: gr.iccs.imu.ems.baguette.server.coordinator.cluster.ClusterZoneDetector
2024-06-26T10:27:04.184Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.b.s.c.TwoLevelCoordinator        : TwoLevelCoordinator.initialize(): Groupings: top-level=GLOBAL, node-level=PER_INSTANCE
2024-06-26T10:27:04.184Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.baguette.server.BaguetteServer   : BaguetteServer.startServer(): Starting SSH server...
2024-06-26T10:27:04.184Z  INFO 30 --- [ taskExecutor-1] gr.iccs.imu.ems.baguette.server.Sshd     : ** SSH server **
2024-06-26T10:27:04.184Z  INFO 30 --- [ taskExecutor-1] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server: Public IP address: 10.0.0.178
2024-06-26T10:27:04.185Z  INFO 30 --- [ taskExecutor-1] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server:  Starting on port: 2222
2024-06-26T10:27:04.185Z  INFO 30 --- [ taskExecutor-1] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server:   Server key file: /opt/ems-server/config/hostkey.pem
2024-06-26T10:27:04.202Z  INFO 30 --- [ taskExecutor-1] gr.iccs.imu.ems.baguette.server.Sshd     : SSH server: Ready
2024-06-26T10:27:04.202Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.b.s.coordinator.NoopCoordinator  : TwoLevelCoordinator: start(): Invoking callback
2024-06-26T10:27:04.203Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.baguette.server.BaguetteServer   : ****************************************
2024-06-26T10:27:04.203Z  INFO 30 --- [       Thread-7] gr.iccs.imu.ems.baguette.server.Sshd     : --> Heartbeat: Started: period=60000ms
2024-06-26T10:27:04.203Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.baguette.server.BaguetteServer   : ****  MONITORING TOPOLOGY IS READY  ****
2024-06-26T10:27:04.203Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.baguette.server.BaguetteServer   : ****************************************
2024-06-26T10:27:04.203Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.baguette.server.BaguetteServer   : BaguetteServer.startServer(): Starting SSH server... done
2024-06-26T10:27:04.206Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator.startNetdataCollector(): Starting NetdataCollector: app-model-id=1216122606rest-processor-app1719396972665.yml
2024-06-26T10:27:04.207Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.c.c.AbstractEndpointCollector    : Collectors::ServerNetdataCollector: Started
2024-06-26T10:27:04.208Z  WARN 30 --- [ taskExecutor-1] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator._processAppModel(): Skipping MetaSolver setup due to configuration
2024-06-26T10:27:04.209Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator._processAppModel(): Cache translation results: app-model-id=1216122606rest-processor-app1719396972665.yml
2024-06-26T10:27:04.210Z  WARN 30 --- [ taskExecutor-1] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator._processAppModel(): Skipping notification due to configuration
2024-06-26T10:27:04.210Z  INFO 30 --- [ taskExecutor-1] sEmsClientDeploymentPostProcessingPlugin : K8sEmsClientDeploymentPostProcessingPlugin: Set applicationId to: 1216122606rest-processor-app1719396972665  -- was: 1216122606rest-processor-app1719396972665
2024-06-26T10:27:04.210Z  INFO 30 --- [ taskExecutor-1] sEmsClientDeploymentPostProcessingPlugin : K8sEmsClientDeploymentPostProcessingPlugin: Start deploying EMS clients...
2024-06-26T10:27:04.227Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.c.c.NodeRegistrationCoordinator  : NodeRegistrationCoordinator.registerNode(): ExecutionWare: PROACTIVE
2024-06-26T10:27:04.229Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.install.ClientInstaller      : ClientInstaller: Executing Client installation Task #0: task-id=K8S-_-dummy-1719397624210-dummy-1719397624210-Kubernetes-_-_, node-id=dummy-1719397624210, name=dummy-1719397624210, type=K8S, address=unknown-address-1719397624227
2024-06-26T10:27:04.229Z  INFO 30 --- [ taskExecutor-1] g.i.i.e.c.c.ControlServiceCoordinator    : ControlServiceCoordinator._processAppModel(): END: app-model-id=1216122606rest-processor-app1719396972665.yml
2024-06-26T10:27:04.237Z  INFO 30 --- [ taskExecutor-1] e.n.ems.service.EmsBootInitializer       : Metric model processing result: {ems-state-change-timestamp=1719397624237, ems-state-message=, ems-state=READY}
2024-06-26T10:27:04.393Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.install.ClientInstaller      : ClientInstaller: Using K8sClientInstaller for task #0
2024-06-26T10:27:04.396Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.i.i.K8sClientInstaller       : K8sClientInstaller: Extra Env.Vars:

2024-06-26T10:27:05.442Z  WARN 30 --- [pool-4-thread-1] i.f.kubernetes.client.internal.SSLUtils  : SSL handshake failed. Falling back to insecure connection.
2024-06-26T10:27:56.509Z  INFO 30 --- [       Thread-6] gr.iccs.imu.ems.baguette.server.Sshd     : --> Heartbeat: Stopped
2024-06-26T10:27:56.562Z  INFO 30 --- [   scheduling-1] g.iccs.imu.ems.control.util.TopicBeacon  : Topic Beacon: updateModelVersion: Model changed:  -> /1216122606rest-processor-app1719396972665.yml, version: 1
2024-06-26T10:27:56.578Z  INFO 30 --- [       Thread-5] .i.i.e.b.b.i.MessageForwarderInterceptor : MessageQueueProcessor: Forward destinations initialized: []
2024-06-26T10:29:14.832Z ERROR 30 --- [pool-4-thread-1] g.i.i.e.b.c.i.i.K8sClientInstaller       : K8sClientInstaller: Failed executing installation instructions for task #0, Exception:

io.fabric8.kubernetes.client.KubernetesClientException: Operation: [patch]  for kind: [ConfigMap]  with name: [ems-client-configmap]  in namespace: [default]  failed.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:159)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:234)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:237)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:252)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.serverSideApply(BaseOperation.java:1172)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.serverSideApply(BaseOperation.java:97)
        at gr.iccs.imu.ems.common.k8s.K8sClient.createConfigMap(K8sClient.java:102)
        at gr.iccs.imu.ems.baguette.client.install.installer.K8sClientInstaller.createEmsClientConfigMap(K8sClientInstaller.java:149)
        at gr.iccs.imu.ems.baguette.client.install.installer.K8sClientInstaller.deployOnCluster(K8sClientInstaller.java:126)
        at gr.iccs.imu.ems.baguette.client.install.installer.K8sClientInstaller.deployOnCluster(K8sClientInstaller.java:120)
        at gr.iccs.imu.ems.baguette.client.install.installer.K8sClientInstaller.executeTask(K8sClientInstaller.java:105)
        at gr.iccs.imu.ems.baguette.client.install.ClientInstallerPlugin.execute(ClientInstallerPlugin.java:15)
        at gr.iccs.imu.ems.baguette.client.install.ClientInstaller.lambda$executeKubernetesTask$6(ClientInstaller.java:232)
        at gr.iccs.imu.ems.baguette.client.install.ClientInstaller.executeInstaller(ClientInstaller.java:180)
        at gr.iccs.imu.ems.baguette.client.install.ClientInstaller.executeKubernetesTask(ClientInstaller.java:222)
        at gr.iccs.imu.ems.baguette.client.install.ClientInstaller.executeTask(ClientInstaller.java:139)
        at gr.iccs.imu.ems.baguette.client.install.ClientInstaller.lambda$addTask$1(ClientInstaller.java:87)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: timeout
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:504)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:524)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:419)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:397)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handlePatch(BaseOperation.java:763)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:232)
        ... 20 common frames omitted
Caused by: java.io.InterruptedIOException: timeout
        at okhttp3.internal.connection.RealCall.timeoutExit(RealCall.kt:398)
        at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:360)
        at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.kt:325)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:209)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        ... 3 common frames omitted
Caused by: java.net.SocketException: Socket closed
        at java.base/sun.nio.ch.NioSocketImpl.endConnect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        ... 4 common frames omitted

2024-06-26T10:29:14.834Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.i.i.K8sClientInstaller       : K8sClientInstaller: Error occurred while executing task #0
2024-06-26T10:29:14.834Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.install.ClientInstaller      : ClientInstaller: Task execution result #0: success=true
2024-06-26T10:29:14.834Z  WARN 30 --- [pool-4-thread-1] g.i.i.e.b.c.install.ClientInstaller      : ClientInstaller: NODE_REGISTRY_ENTRY status is still INSTALLING after executing client installation. Changing to INSTALL_ERROR
2024-06-26T10:29:14.836Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.install.ClientInstaller      : ClientInstaller: Client installation Task #0: result=SUCCESS, duration=130606ms
2024-06-26T10:29:14.837Z  INFO 30 --- [pool-4-thread-1] g.i.i.e.b.c.install.ClientInstaller      : ClientInstaller: Sending SUCCESS execution report for Task #0: destination=ems.client.installation.reports, report={reference=179d5943-9fae-49c5-9150-94a974595eda, requestId=, requestType=INSTALL, deviceIpAddress=unknown-address-1719397624227, timestamp=1719397754837, status=SUCCESS, deviceId=dummy-1719397624210, nodeInfo={}}

```

**Comment by yoctozepto** [comment]
@robert-sanfeliu I think this should be reported against https://github.com/eu-nebulous/monitoring

**Comment by ipatini** [comment]
This seems a temporary failure to connect to Kubernetes API server, but EMS retries every one minute. If this is occurring sporadically it is not a problem.
