### ISSUE TITLE
nebulous-slo-violation-detector CrashLoopBackOff

### ISSUE THREAD

**Issue by Iqqdd99** [eu-nebulous/nebulous#57]
Latest nebulous-slo-violation-detector image is not able to reach Running state:

```
:~$ kubectl logs pods/nebulous-slo-violation-detector-XXXX-XXXX
Sep 26, 2024 7:17:54 AM slo_violation_detector_engine.generic.SLOViolationDetectorStateUtils getPreferencesFileInputStream
INFO: This is the base project path:file:/home/
Sep 26, 2024 7:17:54 AM slo_violation_detector_engine.generic.SLOViolationDetectorStateUtils getPreferencesFileInputStream
INFO: Loading configuration from path: /slo-violation-detector/src/main/resources/config/eu.nebulous.slo_violation_detector.properties
Sep 26, 2024 7:17:54 AM runtime.Main main
INFO: Problem reading input file
java.io.FileNotFoundException: /slo-violation-detector/src/main/resources/config/eu.nebulous.slo_violation_detector.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at slo_violation_detector_engine.generic.SLOViolationDetectorStateUtils.getPreferencesFileInputStream(SLOViolationDetectorStateUtils.java:31)
	at runtime.Main.main(Main.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
```

Environment:
Fresh Nebulous installation.
Image `slo-violation-detector@sha256:71cfd140e0ba71817e391ee343304e3b4b9b0c072bda718c7654abc6f642f1cd`

**Comment by atsag** [comment]
Should be fixed with https://github.com/eu-nebulous/slo-violation-detector/pull/13
